name: Terraform Workflow

on:
  push:
    branches:
      - 'feat/**'
      - 'fix/**'

jobs:
  Terraform_Validate:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: eu-west-1
    steps:
      - id: configure
        run: |
          apk add -U --no-cache jq
      - id: checkout
        uses: actions/checkout@v4
      - id: tf_init
        run: terraform init
      - id: tf_validate
        run: terraform validate
      - id: tf_plan
        run: terraform plan -out tfplan.binary
      - id: json
        run: terraform show -json tfplan.binary | jq '.' > tfplan.json
      - id: artifact
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: tfplan.json
  Checkov:
    runs-on: ubuntu-latest
    container:
      image: bridgecrew/checkov
    needs: Terraform_Validate
    steps:
      - id: artifact_download
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan    
      - id: checkov
        run: checkov -f ./tfplan.json -o junitxml -o cli || true
        